version: 4.6.0-{build}
image: Visual Studio 2017
configuration: Release
clone_folder: c:\projects\nlog

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"'

skip_tags: true
skip_branch_with_pr: true
build_script:
  - ps: .\build.ps1

test_script:
  - msbuild /t:rebuild .\tools\CheckSourceCode\src\ /p:Configuration=Release /verbosity:minimal
  - tools\CheckSourceCode\NLog.SourceCodeTests.exe no-interactive

cache:
  - src\packages -> **\packages.config

nuget:
  disable_publish_on_pr: true

artifacts:
  - path: 'artifacts\*.nupkg'
  - path: 'artifacts\*.snupkg'

deploy:
- provider: NuGet
  api_key:
    secure: DtVDH1ZfIR8E2oDLeSPxfn0WFXw3MCv4WhLkkQQl9LfEHswb5sdxdCYodNKhrKik
  on:
    branch: master